version: '3'
services:
  ionic-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8100:8100"
      - "35729:35729"
      - "53703:53703"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
